version: "3.1"
services:
  db:
    image: library/postgres:latest
    restart: always
    expose:
      - '5432'
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 3s
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/pgsql/1
      - TZ=Europe/Moscow


  authentication:
    image: inozpavel/authentication
    restart: always
    environment:
      - JWT_KEY=RTUITLAbSecretKey123
      - TOKEN_SECONDS_LIFETIME=60
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres
      - TZ=Europe/Moscow
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
    
